trigger:
- master

pool:
  name: 'MakeAgents'
  demands:
  - Agent.OS -equals Linux
  - node.js

steps:
- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: 'src/test-apps/hello-world-ng'
