apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-linux-agents-deployment
  labels:
    app: azdox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdox
  template:
    metadata:
      labels:
        app: azdox
    spec:
      containers:
      - name: azdo
        image: giuliovprodemo.azurecr.io/azure-pipelines-agent/linux/angular:latest
        env:
          - name: AZP_URL
            valueFrom:
              configMapKeyRef:
                name: azurepipeline-config
                key: azurepipeline-url
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azurepipeline-token
                key: azurepipeline-token
          - name: AZP_POOL
            valueFrom:
              configMapKeyRef:
                name: azurepipeline-config
                key: azurepipeline-pool
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      nodeSelector:
        kubernetes.io/os: linux



